// Admin pages
export { default as CategoriesEdit } from "./admin/categories/edit"
export { default as Categories } from "./admin/categories/list"
export { default as AdminHome } from "./admin/index"
export { default as AdminOrders } from "./admin/orders/list"
export { default as AdminOrdersSingle } from "./admin/orders/single"
export { default as ProductAdd } from "./admin/product/add"
export { default as ProductEdit } from "./admin/product/edit"
export { default as AdminProductList } from "./admin/product/list"
export { default as HomePage } from "./home"
// User pages
export { default as UserCart } from "./user/cart/index"
export { default as ProductList } from "./user/product/list"
export { default as ProductSingle } from "./user/product/single"
export { default as UserProfileHome } from "./user/profile/home"
export { default as UserProfile } from "./user/profile/index"
export { default as UserProfileOrder } from "./user/profile/order/list"
export { default as UserProfileOrderSingle } from "./user/profile/order/single"
